Development
AleksanderStudnicki/OX pull request #1
Opened 2019-12-20 08:40 UTC by AleksanderStudnicki

Simple template of project with some of basic features. There is no game logic right now/

2019-12-20 09:28 UTC, mkulikiewicz requested changes
Good luck :+1:

2019-12-20 09:28 UTC, mkulikiewicz commented on pom.xml
> +            <version>7.0.0</version>
Add this value to properties

2019-12-20 09:28 UTC, mkulikiewicz commented on pom.xml
> +                <version>3.8.2</version>
Add this value to properties

2019-12-20 09:28 UTC, mkulikiewicz commented on pom.xml
> +                <version>3.0.0</version>
Add this value to properties

2019-12-20 09:28 UTC, mkulikiewicz commented on src/test/java/app/studnicki/ox/ScoreTest.java
> +package app.studnicki.ox;
This class should be in same package as implementation class. Pls move it to app.studnicki.ox.game.
After this move you can change access your implementation class to package-private

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/game/round/RoundState.java
> +public interface RoundState {
This interface is never used :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/game/Game.java
> +public class Game {
This class is never used :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/game/Player.java
> +public class Player {
This class is never used :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/config/Config.java
> +public class Config {
This is public class javadoc is required here :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/config/Config.java
> +  public ResourceBundle getRb() {
This is public method javadoc is required here :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/config/Config.java
> +  public void changeLanguage(String code) {
This is public method javadoc is required here :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/config/Config.java
> +  public static Config getInstance() {
This is public method javadoc is required here :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/game/Score.java
> +  public void addWin() {
This is public method javadoc is required here :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/game/Score.java
> +  public void addDraw() {
This is public method javadoc is required here :(

2019-12-20 09:28 UTC, mkulikiewicz commented on src/main/java/app/studnicki/ox/game/gamestate/PlayersInitState.java
> +public class PlayersInitState implements GameState {
This is public class javadoc is required here :(

2019-12-22 09:05 UTC, marcinogo commented on pom.xml
> +
Nie potrzeba aż tyle odstępu. 1 linia była wystarczająca.

2019-12-22 09:07 UTC, marcinogo commented on src/main/java/app/studnicki/ox/Main.java
> +
Zbędne odstępy. Zrób na każdej klasie `CTRL+ALT+L` - autoreformat w *Intellij*.

2019-12-22 09:10 UTC, marcinogo commented on src/main/java/app/studnicki/ox/Main.java
> +            break;
Można by to zamknąć w metodzie. Możliwe, że nawet w metodzie innej klasy.

2019-12-22 09:11 UTC, marcinogo commented on src/main/java/app/studnicki/ox/Main.java
> +    }
Całość można by zamknąć w metodzie wywoływanej tylko z `main()`.

2019-12-22 09:16 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/Board.java
> +public class Board {
Klasa publiczna, ale bez javadoc :(

2019-12-22 09:19 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/WinningRule.java
> +public class WinningRule {
Zadeklarowane, ale niezaimplementowane i najpewniej nie używane jeszcze. YAGNI.

2019-12-22 09:19 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/gamestate/GameState.java
> +public interface GameState {
Javadoc

2019-12-22 09:21 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/PlayerBuilder.java
> +public class PlayerBuilder {
Javadoc

2019-12-22 09:21 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/Score.java
> +public class Score {
A jak by tak zrobić z tego enum?

2019-12-22 09:24 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/gamestate/GameStateFactory.java
> +public class GameStateFactory {
Nazwa *factory* sugerowałaby, że w jakiś sposób jesteśmy w stanie utworzyć różne `GameState` w tej klasie. Wydaje mi się, że nazwa nie odzwierciedla zamysłu.

2019-12-22 09:25 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/gamestate/GameStateFactory.java
> +public class GameStateFactory {
Publiczne bez javadoc

2019-12-22 09:27 UTC, marcinogo commented on src/main/resources/Message_ja.properties
> +score = スコア
*NANII*, ale szacunek za Japoński :P

2019-12-22 09:28 UTC, marcinogo commented on src/main/resources/Message_ja.properties
> +welcome = ○×ゲーム. ようこそ!
Sprawdź czy nie ma jakiejś konwencji nazewniczej plików `.properties` dla ResourceBundle.

2019-12-22 09:28 UTC, marcinogo commented on src/main/resources/Message_en.properties
> +welcome = Tic Tac Toe. Welcome!
Sprawdź czy nie ma jakiejś konwencji nazewniczej plików `.properties` dla ResourceBundle.

2019-12-22 09:29 UTC, marcinogo commented on src/main/resources/Message_pl.properties
> +welcome = Kółko i krzyżyk. Witaj!
Sprawdź czy nie ma jakiejś konwencji nazewniczej plików `.properties` dla ResourceBundle.

2019-12-22 09:29 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/UserInterfaceFactory.java
> +public class UserInterfaceFactory {
Javadoc

2019-12-22 09:30 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/UserInterface.java
> +public interface UserInterface {
Javadoc

2019-12-22 09:32 UTC, marcinogo commented on src/main/resources/Message.properties
> +welcome = Tic Tac Toe. Welcome!
Sprawdź czy nie ma jakiejś konwencji nazewniczej plików .properties dla ResourceBundle oraz czy nie dało by się jakoś domyślnego spiąć z angielskim by nie duplikować tego (możlwie, że nie).

2019-12-22 09:36 UTC, marcinogo commented on src/main/java/app/studnicki/ox/initstate/InitStateFactory.java
> +public class InitStateFactory {
Podobnie jak przy `GameStateFactory`.

2019-12-22 09:38 UTC, marcinogo commented on src/test/java/app/studnicki/ox/ScoreTest.java
> +   */
Klasy testowe nie potrzebują javadoc. Testy same powinny tłumaczyć co się dzieje.

2019-12-22 09:39 UTC, marcinogo commented on src/test/java/app/studnicki/ox/ScoreTest.java
> +  }
Podziel sobie te metody testowe za pomocą komentarzy na części (konwencja *AAA* lub *GWT*).

2019-12-22 09:40 UTC, marcinogo commented on src/test/java/app/studnicki/ox/ScoreTest.java
> +//STATIC
Zbędne

2019-12-22 09:40 UTC, marcinogo commented on src/test/java/app/studnicki/ox/ScoreTest.java
> +//NON STATIC
Zbędne

2019-12-22 09:43 UTC, marcinogo commented on src/test/java/app/studnicki/ox/ScoreTest.java
> +public class ScoreTest {
Można by popracować nad nazwami metod testowych np. *add* zamiast *added* albo tej ostatniej tak by  podpadała pod konwencję `should...`. Zasadniczo obierz 1 konwencję i się jej trzymaj.

Tu stosowny artykuł: https://dzone.com/articles/7-popular-unit-test-naming

2019-12-22 09:50 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +public class GameBuilder {
Rozdzieliłbym budowanie graczy od budowy gry i przekazywałbym tylko gotową listę graczy jako 1 ze składowych. Nie widze też możliwości konfiguracji rozmiaru planszy tutaj, w przeciwieństwie do warunku wygranej.

2019-12-22 09:50 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +public class GameBuilder {
Javadoc

2019-12-22 09:50 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +  public GameBuilder winningRule(WinningRule winningRule) {
Javadoc

2019-12-22 09:51 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +  public GameBuilder firstPlayerName(String name) {
J.w.

2019-12-22 09:51 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +  public GameBuilder secondPlayerName(String name) {
J.w.

2019-12-22 09:51 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +  public GameBuilder firstPlayerSign(Sign sign) {
J.w.

2019-12-22 09:51 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +  public GameBuilder userInterface(UserInterface userInterface) {
J.w.

2019-12-22 09:51 UTC, marcinogo commented on src/main/java/app/studnicki/ox/game/GameBuilder.java
> +  public Game build() {
J.w.

2019-12-22 09:52 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/ConsoleUserInterface.java
> +  }
YAGNI

2019-12-22 09:53 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/ConsoleUserInterface.java
> +    out.println(rb.getString("exitChoice"));
Można by pokusić się o zmianę na `printf` z odpowiednią składnią.

2019-12-22 09:54 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/ConsoleUserInterface.java
> +    out.println(rb.getString("changeLanguageMenu"));
J.w.

2019-12-22 09:54 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/ConsoleUserInterface.java
> +//
?

2019-12-22 10:06 UTC, marcinogo commented on src/main/java/app/studnicki/ox/ui/ConsoleUserInterface.java
> +  private ResourceBundle rb = Config.getInstance().getRb();
Można by zrobić dedykowaną metode w klasie Config zamiast zwracać kolejkę getów.

2019-12-22 10:12 UTC, marcinogo requested changes
Po odpaleniu nie działa opcja na wyjście z aplikacji. Dodatkowo trzeba wklepać *X* lub *O* wielką literą (a można, by wejście użytkownika robić do dużych liter z automatu).

Javadoc byłyby miłym dodatkiem, ale nie spędzaj nad nimi za dużo czasu.

Martwi mnie też pokrycie testami.

2019-12-22 20:24 UTC, LIttleAncientForestKami commented
I've left my remarks as issues.

2019-12-22 22:23 UTC, LIttleAncientForestKami requested changes
See issues - especially #6

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on pom.xml
>      <version>0.1</version>
Really?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on pom.xml
> +                            <mainClass>app.studnicki.ox.Main</mainClass>
:+1:

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on pom.xml
> +                <version>3.0.0</version>
This is generally true for all version values.

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Main.java
> +package app.studnicki.ox;
Nice main package. But... why app as the first part?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Main.java
> +    menu.run();
Could be done as one line: `new Menu(UserInterfaceFactory.console()).run();`
Since you don't need to reuse vars, why not do it like that?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Main.java
> +public class Main {
Why public?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Menu.java
> +    switch (ui.changeLanguage()) {
How does a switch help with OO? Why not have an enum with available languages and switch on enum? Why not reduce the complexity by making enumMap with messages and just load it (or reload it) from a resource bundle depending on language code? Why allow choosing an int if you could just ask a user to type two letters from en/pl/ja and use them to search for a language key in enumMap languages and catch the error if there is no such key reducing the complexity?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Menu.java
> +      int choice = ui.menu();
is there a need for this variable? If it's only used in switch, why not `switch(ui.menu())`?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Menu.java
> +          exit = true;
What would happen if you just returned here?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Menu.java
> +  private void runGame() {
Why on earth is this a private method of the Menu class? :hurtrealbad:

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/Sign.java
> +public enum Sign {
Hatred for Javadocs or Javadoc-phobia? Even with both, you still will need to write some. :P

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/game/Coordinates.java
> +  int x;
Package-private fields because?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/game/Coordinates.java
> +public class Coordinates {
Why would you need that concept? What it gives you?

2019-12-22 22:23 UTC, LIttleAncientForestKami commented on src/main/java/app/studnicki/ox/game/Game.java
> +public class Game {
:hurtrealbad:

2019-12-30 23:18 UTC, closed without merging